### ISSUE TITLE
URL設計をする

### ISSUE THREAD

**Issue by R-Tsukada** [R-Tsukada/football-myteam#11]

**Comment by R-Tsukada** [comment]
|  method  |  path  | description
| ---- | ---- | ---- |
|GET|/|トップページ（サービス説明画面）を表示する|
|GET|/users/new|ユーザー新規登録画面を表示する|
|POST|/users/new|ユーザーの新規登録をする|
|GET| /login|ログイン画面を表示する|
|GET|/teams|チームをお気に入り登録をする画面を表示する|
|POST|/teams|チームのお気に入り登録をする|
|GET|/schedules|お気に入り登録したチームの試合予定、チーム情報を表示する|
|DELETE|/schedules|お気に入り登録したチームを削除する|
|GET|/schedules/:team_id|お気に入り登録したチームの試合予定、結果の詳細を表示する|
|GET|/users/edit|ユーザー情報変更画面を表示する|
|POST|/users/edit|ユーザー情報を変更する|

**Comment by kfukai23** [comment]
- `POST /users/new` は `POST /users` になると思います〜
- `POST	/teams チームのお気に入り登録をする` ですが、この verb + URL だと REST 的には team そのものを新規登録する、という意味になります。新規登録したいリソースは favorites だと思うのでそちらに置き換えるのがよさそうです
  - 伴って、`GET /teams チームをお気に入り登録をする画面を表示する` も「favorites 新規登録画面」と考えて URL を見直してみてください
  - `DELETE	/schedules	お気に入り登録したチームを削除する` こちらも削除対象リソースが schedule そのものであるように見える形になってしまっているので、favorites にしましょう
- `GET /schedules/:team_id お気に入り登録したチームの試合予定、結果の詳細を表示する` ですが、実際の URL だと `/schedules/4` という形になりますね。REST 的には、これだと `4` が Team ではなく Schedule の id に見えてしまうんですよね（`/複数形のリソース名/左記のリソースのid` という形が基本なので）。「スケジュールのうち特定のチームを指定している」とわかるようにしたいので、`/schedules/teams/:team_id` とかが良いかもしれません。
- `POST	/users/edit	ユーザー情報を変更する` ですが POST ではなく PATCH ですね（更新なので）。パスも `/users/edit` ではなく `/users` が適切です

**Comment by R-Tsukada** [comment]
コメントありがとうございます！
指摘していただいた点を修正しました。DB設計の方でも書かせてもらったのですが、「応援しているチーム」と「ライバルチーム」のモデルを分けました。その関係でお気に入り登録のパスを2種類に分けました。「応援しているチーム」を「favorite」、「ライバルチーム」を「competitor」というパスにしています。

|  method  |  path  | description
| ---- | ---- | ---- |
|GET|/|トップページ（サービス説明画面）を表示する|
|GET|/users/new|ユーザー新規登録画面を表示する|
|POST|/users|ユーザーの新規登録をする|
|GET|/users/edit|ユーザー情報変更画面を表示する|
|PATCH|/users|ユーザー情報を変更する|
|GET| /login|ログイン画面を表示する|
|GET|/favorites|応援しているチームのお気に入り登録をする画面を表示する|
|POST|/favorites|応援しているチームのお気に入り登録をする|
|DELETE|/favorites|お気に入り登録した応援しているチームを削除する|
|GET|/competitor|ライバルチームのお気に入り登録をする画面を表示する|
|POST|/competitor|ライバルチームのお気に入り登録をする|
|DELETE|/competitor|お気に入り登録したライバルチームを削除する|
|GET|/schedules|お気に入り登録したチームの試合予定、チーム情報を表示する|
|GET|/schedules/teams/:team_id|お気に入り登録したチームの試合予定、結果の詳細を表示する|

**Comment by kfukai23** [comment]
修正ありがとうございます！概ねOKだと思います:ok_hand:

> GET  /competitor ライバルチームのお気に入り登録をする画面を表示する
> GET  /favorites 応援しているチームのお気に入り登録をする画面を表示する

この2つは /competitor**/new** になるのが適切な気がします（ competitor というリソースの新規登録画面なので。/users/new とかと同じです）
それ以外はよさそうです！

**Comment by R-Tsukada** [comment]
> 修正ありがとうございます！概ねOKだと思います👌

ありがとうございます！

> この2つは /competitor**/new** になるのが適切な気がします（ competitor というリソースの新規登録画面なので。/users/new とかと同じです）

承知しました！ご指摘ありがとうございます🙏

**Comment by R-Tsukada** [comment]
## 修正版

|  method  |  path  | description
| ---- | ---- | ---- |
|GET|/|トップページ（サービス説明画面）を表示する|
|GET|/users/new|ユーザー新規登録画面を表示する|
|POST|/users|ユーザーの新規登録をする|
|GET|/users/edit|ユーザー情報変更画面を表示する|
|PATCH|/users|ユーザー情報を変更する|
|GET| /login|ログイン画面を表示する|
|GET|/favorites/new|応援しているチームのお気に入り登録をする画面を表示する|
|POST|/favorites/|応援しているチームのお気に入り登録をする|
|DELETE|/favorites|お気に入り登録した応援しているチームを削除する|
|GET|/competitor/new|ライバルチームのお気に入り登録をする画面を表示する|
|POST|/competitor|ライバルチームのお気に入り登録をする|
|DELETE|/competitor|お気に入り登録したライバルチームを削除する|
|GET|/schedules|お気に入り登録したチームの試合予定、チーム情報を表示する|
|GET|/schedules/teams/:team_id|お気に入り登録したチームの試合予定、結果の詳細を表示する|

**Comment by kfukai23** [comment]
LGTM！修正ありがとうございました:pray:
